version: "3.7"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    image: buivanhuu2017/bigtreeland-client:production
    deploy:
      replicas: 1
    ports:
      - 80:80
